### PR TITLE
Dice service unit test

### PR DESCRIPTION
**Pull request by cvillhauer**

### CODE REVIEW

**Comment by cvillhauer** [comment]
@rdrrichards Maybe run the dice roller 1000 times and make sure the max value of all the results is what we'd expect? That the average is in some kind of ballpark?

**Comment by rdrrichards** [comment]
Good idea! I have never looked into the idea that I unit test would iterate like that, but I think that could work. As long as it's quick... we might be good.

**Comment by cvillhauer** [comment]
@rdrrichards Give it a try if you'd like! This PR can wait. I'm going to make a new branch and work on some of the smaller issues I listed out the other day. The complicated Attacks stuff will have to wait until I have more brain power :-)

**Comment by rdrrichards** [comment]
All is good! I will give it a go.

**Comment by cvillhauer** [comment]
@rdrrichards What about this pull request? Should we still do it, or do you first want to edit some unit test code? Or is this too out of date at this point?

**Pull request merged**
